#!/bin/sh
export PHP_VERSION=71

export APP_NAME=dribly-users
export NGINX_HOSTNAME=dribly-users
echo "${APP_NAME} going down"
export CONTAINER_NAME_PREFIX=${APP_NAME}

echo ${APP_NAME}
docker-compose --project-name="Dribly" down --rmi all
echo "All done downing ${APP_NAME}. Hope it worked"

